#!/usr/bin/env bash
# Run Nginx as Nginx

sudo service nginx stop
echo "user nginx;" >> /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80/8080 default_server/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart